server:
  port: 9000
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
           client-id: api-gateway-app
           client-secret: 7rizxEa1DnrQCD9KtbHFGmV5DHp3Gpmr
           authorization-grant-type: authorization_code
           scope: openid email profile
           redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myrealm
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: my-book-service
          uri: lb://book-service
          predicates: 
            Path=/books/**
        - id: my-lib-service
          uri: lb://library-service
          predicates: 
           Path=/library/**
          filters:
          - name: CircuitBreaker
            args:
              id: cb1
              name: backendB
              fallbackUri: forward:/library-fallback
              
        - id: test-url
          uri: http://google.co.in
          predicates: 
           Path=/redirect/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j.circuitbreaker:
     instances:
      backendB:
       registerHealthIndicator: true
       slidingWindowSize: 10
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowType: COUNT_BASED
       minimumNumberOfCalls: 15
       waitDurationInOpenState: 30s
       failureRateThreshold: 40
       eventConsumerBufferSize: 10
       automaticTransitionFromOpenToHalfOpenEnabled: true
logging:
  level:
    '[org.springframework.security]': debug
    '[org.springframework]': error
